### ISSUE TITLE
Gensim update breaks pecanpy due to size vs vector_size argument

### ISSUE THREAD

**Issue by CalvinLeather** [krishnanlab/PecanPy#16]
Gensim has changed the size keyword argument to vector_size in genesis ~4. This broke pecanpy, as it pins gensim  >=3.8.0. 

The resulting traceback looks like:

```
Traceback (most recent call last):\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/bin/pecanpy", line 8, in <module>\n    sys.exit(main())\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/lib/python3.7/site-packages/pecanpy/cli.py", line 182, in main\n    main_helper(parse_args())\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/lib/python3.7/site-packages/pecanpy/cli.py", line 177, in main_helper\n    timed_emb()\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/lib/python3.7/site-packages/pecanpy/wrappers.py", line 18, in wrapper\n    result = func(*args, **kwargs)\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/lib/python3.7/site-packages/pecanpy/cli.py", line 171, in timed_emb\n    learn_embeddings(args=args, walks=walks)\n  File "/usr/local/Caskroom/miniconda/base/envs/pipeline/lib/python3.7/site-packages/pecanpy/cli.py", line 148, in learn_embeddings\n    iter=args.iter,\nTypeError: __init__() got an unexpected keyword argument \'size\'\n
```

I will probably open a PR once I identify the breaking version (either to ping the version or just to fix the keyword argument usage), maybe later today, but opening this in case I forget so others can see. The easy fix is just to pin gensim at 3.8 locally.

Backup source on breaking changes: https://stackoverflow.com/questions/53195906/getting-init-got-an-unexpected-keyword-argument-document-this-error-in

**Comment by RemyLau** [comment]
Hi, this is resolved in the newest release (see this [commit](https://github.com/krishnanlab/PecanPy/commit/e7a195f59b9f057c2cfafffd9deb6c8d0e3ff01d))!
